### ISSUE TITLE
Php script for website

### ISSUE THREAD

**Issue by Shahjee703** [bogkonstantin/android_income_sms_gateway_webhook#1]
Hello Sir,
I just tested your app and I appreciate your effort for the community .
I am creating my college project and this is the what i was looking for.

Can you please share PHP script file to access the msg data we get on website ?

I will really thankful to you.

Regards.

**Comment by bogkonstantin** [comment]
Hi. Sorry, I don't have one. Use $_POST variable in PHP to use data.
If you want to see the payload, try this website: https://webhook.site/

**Comment by Shahjee703** [comment]
Okay get it. Thanks for your reply.

**Comment by jpph** [comment]
see https://github.com/bogkonstantin/android_income_sms_gateway_webhook/issues/21 with example
