### ISSUE TITLE
Serverside data?

### ISSUE THREAD

**Issue by kimi1976** [bogkonstantin/android_income_sms_gateway_webhook#10]
In what format gateway send data to server?

$_POST, $_GET etc are all empty.

I'm using PHP on server side, and this apk loads PHP file when there is new SMS in phone.

But I can't get message text out from reguest.

If these informations are somewhere in documents ... I couldn't find it ..

**Comment by bogkonstantin** [comment]
Content-type is application/json, so in PHP you should use file_get_contents('php://input')

**Comment by kimi1976** [comment]
HI.

Thanks for a quick answer ... 

from CURL example in README.dm I can get data in $message {"from":"1234567890","text":"Test"}, but from app $message is empty.

my code : 
$date = date('d.m.Y h:i:s a', time()); 
$json = file_get_contents("php://input");
$message = $json;
$fp = fopen('SMS_2016.log', 'a');
	fwrite($fp, '-GitHub SMS Forwarder'.PHP_EOL.$date.PHP_EOL.$message.PHP_EOL);
	fclose($fp);
?>

**Comment by bogkonstantin** [comment]
1 Is your sender name or number is exactly the same as in the default SMS app? Try to check with * (asterisk) instead of a number to resend all SMS to URL.
2 If still no request - can you check logs on your phone on your android device? (reading logcat with adb cli tool or android studio desktop app).

**Comment by kimi1976** [comment]
1. Sender is *, and when I receive SMS, App will get connect to PHP-script. But there is no payload on php://input.

7:31 and 7:40 LOG's are from App, 7:52 LOG is from CURL.

-GitHub SMS Forwarder-------------------------------------------------------------------------------
13.08.2021 07:31:22 am

-GitHub SMS Forwarder-------------------------------------------------------------------------------
13.08.2021 07:40:01 am

-GitHub SMS Forwarder-------------------------------------------------------------------------------
13.08.2021 07:52:02 am
{"from":"12345678","text":"Message text"}

**Comment by bogkonstantin** [comment]
At least we have request)

Try to use https://webhook.site/ instead your URL. Is it still empty?

**Comment by kimi1976** [comment]
in webhook.site there is payload .....

**Comment by bogkonstantin** [comment]
So app sends it. 

Check your webserver/php configuration.
> php://input content does not get through if request is redirected. Maybe your web server has a redirect from an URL starting with www to an URL without www, or from URLs using HTTP to URLs using HTTPS. Check your web server logs to verify this

https://stackoverflow.com/questions/19146984/file-get-contentsphp-input-always-returns-an-empty-string/58101656

https://stackoverflow.com/questions/11990767/post-empty-when-curling-json

**Comment by kimi1976** [comment]
I don't have access to server configuration ....

PHP-script works with CURL command from my Linux PC.

App works to Webhook, but not to PHP-script ...

**Comment by bogkonstantin** [comment]
App sends payload, you saw it. 

The app doesn't know what script is using on your web server, it just sends, that's it. Then your webserver process it (Nginx or Apache I guess). And drops the payload somewhere. 

There is only one way to check your web server logs/configs. I suggest you check if there are any redirects at first (as stated in the resources I found for you in the previous message).

**Comment by kimi1976** [comment]
Yes, app sends the payload, so it works :)

Strange things is that curl works, app don't.

I guess I need to build up one extra server with Apache, to receive SMS from app, and pass them to main server ... In that way I have access to server configuration.

Thank you for help :)

**Comment by jpph** [comment]
see https://github.com/bogkonstantin/android_income_sms_gateway_webhook/issues/21
maybe related
