### ISSUE TITLE
[feature request] customisable json payload key-value pairs

### ISSUE THREAD

**Issue by shtingeri** [bogkonstantin/android_income_sms_gateway_webhook#11]
It'd be great if json payload  key names can be customisable instead of the default` {"from":"1234567890","text":"Test"}`.
A lot of existing webhooks require different json key names, e.g.   `{"key1":"1234567890","key2":"Test"}`
Or accept only one key-value pair , e.g. ` {"key":"value"}`

**Comment by bogkonstantin** [comment]
[Released](https://github.com/bogkonstantin/android_income_sms_gateway_webhook/releases/tag/2.1.1)
