### ISSUE TITLE
SMS  not forwarding to URL

### ISSUE THREAD

**Issue by aniakg** [bogkonstantin/android_income_sms_gateway_webhook#12]
Hi,
I have configured the webhook URL as per your instructions but still not getting any data on the URL.

Can you please help me

**Comment by bogkonstantin** [comment]
Did you test your server-side using curl sample?

**Comment by jpph** [comment]
see https://github.com/bogkonstantin/android_income_sms_gateway_webhook/issues/21
you have to decode json manually
