### ISSUE TITLE
Need to run apk in background process..

### ISSUE THREAD

**Issue by rtraselbd** [bogkonstantin/android_income_sms_gateway_webhook#14]
When I run this apk it works fine upto 10-20 minutes.. 

But it should run continue in background process..

**Comment by bogkonstantin** [comment]
Please, provide more details. What Android version do you use, did you check battery saver option or restricting app background activities in the Settings?

**Comment by RtRaselBD** [comment]
I am using android 6

**Comment by hank-milliken** [comment]
Same issue here on Android 11.

@bogkonstantin The problem is that on modern Android there is quite aggressive policy that stops any app in the background.

The change was introduced here: https://developer.android.com/about/versions/oreo/background#services

The solution is to create Foreground Service (https://developer.android.com/guide/components/foreground-services) that keeps Sticky Notification.

**Comment by bogkonstantin** [comment]
@hank-milliken thanks for suggestion, moved to the Foreground Service
https://github.com/bogkonstantin/android_income_sms_gateway_webhook/releases/tag/2.1.1

**Comment by hank-milliken** [comment]
@bogkonstantin amazing, I am really sorry that I found this soooooooo late (I complately forgot to check my mail on this account).

I am using it immediately with ntfy.sh and it woooorks sooooo well. No I am forwarding texts from my old phone that can sit at home to my anonymous phone that has no sim and is always in flght mode.

**Comment by hank-milliken** [comment]
Thank you very much. Please gimme some Lightning Address so I can send some Bitcoin your way!

**Comment by Creogenesis** [comment]
> @bogkonstantin amazing, I am really sorry that I found this soooooooo late (I completely forgot to check my mail on this account).
> 
> I am using it immediately with [ntfy.sh ](https://ntfy.sh/) and it woooorks sooooo well. No I am forwarding texts from my old phone (that can sit safely at home) to my anonymous phone that has no sim and is always in flight mode.

Hi,

Please give me your example of setting up ntfy. I have a self-hosted ntfy with a password, and I can't figure out what's wrong with my configuration.

**Comment by hank-milliken** [comment]
@Creogenesis Everything works well. Sorry I was just sharing my happiness. I had a small typo in original comment that may cased the confusion.
