### ISSUE TITLE
add to field

### ISSUE THREAD

**Issue by jacob019** [bogkonstantin/android_income_sms_gateway_webhook#15]
I love this app and it's simplicity, thank you for your work. I run it on multiple devices and I can't tell which device messages were sent to. It would be nice to have a to field included in the JSON message. If it is difficult to get the information from android, then it could be a config value instead. Just a suggestion. Thanks again.

**Comment by bogkonstantin** [comment]
[Released](https://github.com/bogkonstantin/android_income_sms_gateway_webhook/releases/tag/2.1.1)
