### ISSUE TITLE
Allow to include message or source number in the URL

### ISSUE THREAD

**Issue by pjamargh** [bogkonstantin/android_income_sms_gateway_webhook#18]
It would be useful to have a way of referring to the phone number or message in the URL used for the webhook (something like $PHONE and $MESSAGE). This way it would be trivial to make it send a message to something like Telegram messenger.

Both variables should create URL encoded data so they're usable.

**Comment by SamSirry** [comment]
How can this help sending to Telegram? Aren't you going to be sending to a bot, which eventually will process the HTTP Request Body anyway?

**Comment by pjamargh** [comment]
I'm sending that directly to Telegram servers. Just with an auth token+the appropriate parameters in the query string would send a message to a chatroom or user. I actually made the change myself to support this use case (probably in a hacky way). I can send you a pull request but at least there is work to do updating the app strings to inform the user those keywords can be used in the URL.

**Comment by SamSirry** [comment]
Thank you, this is beyond my expertise, but I believe that using a Telegram Bot is the better/correct way to do it.

**Comment by mpuz** [comment]
@pjamargh - hello, can you share the pull request with me? I need to add token and one more extra field

**Comment by umer0586** [comment]
@mpuz Custom JSON fields can be added by adding `messageData.put("Custom field", "value")`  under 

https://github.com/bogkonstantin/android_income_sms_gateway_webhook/blob/4fdc0da51651fcfac02715ea5ac8720bb27d7e54/app/src/main/java/tech/bogomolov/incomingsmsgateway/SmsReceiver.java#L88-L99

But this also requires to update UI to take custom fields from user

**Comment by bogkonstantin** [comment]
Custom JSON fields was added in the 2.1.1 release and sample config for Telegram in the Readme
