### ISSUE TITLE
Important SMS missed

### ISSUE THREAD

**Issue by cashmaal** [bogkonstantin/android_income_sms_gateway_webhook#2]
Hi bro, 
 I want to send an SMS if some time internet disconnect. or app closed, or mobile OFF.  any case message will be not missed, when we open the app again, the previous SMS will developer as soon as possible. and some time you send SMS to web but, website can be temporary close, that's why get response from website also.

**Comment by bogkonstantin** [comment]
Implemented in new [release](https://github.com/bogkonstantin/android_income_sms_gateway_webhook/releases/tag/2.0)
