### ISSUE TITLE
net receiving body of payload

### ISSUE THREAD

**Issue by jdetmold** [bogkonstantin/android_income_sms_gateway_webhook#20]
from an android 11 device I am only able to receive the following payload but it seems to come with no body

{
"headers": {
"Connection": "Keep-Alive",
"Transfer-Encoding": "chunked",
"Accept-Encoding": "gzip",
"Host": "myurl.com",
"User-Agent": "SMS,Forwarder,App",
"Content-Type": "application/json; charset=utf-8",
"Content-Length": "0"
}
}

any help would be amazing!

**Comment by jpph** [comment]
see https://github.com/bogkonstantin/android_income_sms_gateway_webhook/issues/21 , might be related
