### ISSUE TITLE
php json empty post issue

### ISSUE THREAD

**Issue by jpph** [bogkonstantin/android_income_sms_gateway_webhook#21]
Took me a while to understand why my post var was empty, it is because of the json type! I think would be nice to add in the doc that you have to decode it manually in php script. Or include an example:

```
<?php

$_POST = json_decode(file_get_contents('php://input'), true);

$text = "N/A";
if(isset($_POST["text"])){
     $text =  $_POST["text"];
}
$from = "N/A";
if(isset($_POST["from"])){
    $from =  $_POST["from"];
}
mail ( "xxx@gmail.com", "from ".$from, $text);
echo "OK";
?>
```

**Comment by bogkonstantin** [comment]
https://github.com/bogkonstantin/android_income_sms_gateway_webhook#process-payload-in-php-scripts
