### ISSUE TITLE
Multiple length (160+ characters) are getting sent in chunks of 160 characters.

### ISSUE THREAD

**Issue by davchana** [bogkonstantin/android_income_sms_gateway_webhook#22]
Normally, a sms consist of 160 characters, for carrier sms counting purposes, and also in old phones. But all new phones are capable of displaying longer than 160+ characters sms as one msg.

This app should also not split the msg at 160 characters length; & instead should send all complete sms as one request.

For longer msgs, I receive multiple requests from app to my server, all with text at maximum 160 characters length.

Note that many Unicode characters are counted as 2+ character.

**Comment by davchana** [comment]
Sample split text (Unicode characters, but app split normal English characters too, at 160 length)

Chunk 01:
`रोमिंग में भी पाएं अनलिमिटेड कॉल सभी नेटवर्क पर, डाटा बेनिफिट के सा
`
Chunk 03
`थ! किसी भी शहर में एयरटेल थैंक्स ऐप या रिटेलर से रीचार्ज करें u.air`

Chunk 03
`tel.in/MG23`

**Comment by parsibox** [comment]
i also had this problem

**Comment by imadhui** [comment]
So, what's the solution?

**Comment by ArtemYurov** [comment]
Yes, have solution?

**Comment by 2naive** [comment]
@bogkonstantin could you please help with fix like this: https://github.com/aosp-mirror/platform_packages_apps_mms/blob/master/src/com/android/mms/transaction/SmsReceiverService.java#L495

Same problem with multiple PDUs in one message.

**Comment by bogkonstantin** [comment]
[Released](https://github.com/bogkonstantin/android_income_sms_gateway_webhook/releases/tag/2.1.1)

**Comment by davchana** [comment]
> [Released](https://github.com/bogkonstantin/android_income_sms_gateway_webhook/releases/tag/2.1.1)

👍🏻👍🏻 Thanks a lot
