### ISSUE TITLE
Feature Request: Edit record button and sent message report/log

### ISSUE THREAD

**Issue by muava12** [bogkonstantin/android_income_sms_gateway_webhook#23]

**Comment by rockstorm101** [comment]
Hi, thanks for this program. It'd be great to add an "Edit" button to edit entries. It's a pain to have to re-type the JSON template just because you missed on letter :P

**Comment by o-data** [comment]
Seconding this request. Thank you.

**Comment by bogkonstantin** [comment]
Done in [v.2.3.0](https://github.com/bogkonstantin/android_income_sms_gateway_webhook/releases/tag/v.2.3.0)
