### ISSUE TITLE
[feature request] Add Custom JSON fields

### ISSUE THREAD

**Issue by mpuz** [bogkonstantin/android_income_sms_gateway_webhook#24]
If possible, please add methods for adding custom JSON fields and headers for sending  security tokens and id information, like:
```
{ 
   from: "Bob",
   text: "Received text",
   token: "f4398fqp9384urpa984", // this is custom field set by user
   someid: "2345293845298347502987" // another one  field set by user
 }
 ```
 
also possibility of setting POST or GET type will not be superfluous

**Comment by bogkonstantin** [comment]
[Released](https://github.com/bogkonstantin/android_income_sms_gateway_webhook/releases/tag/2.1.1)
