### ISSUE TITLE
Feature request: Tried with Android 4.4.2 but not triggering URL

### ISSUE THREAD

**Issue by narcisgarcia** [bogkonstantin/android_income_sms_gateway_webhook#26]
I've developed PHP backend that works perfectly with curl test, but when I'm trying with an Android Phone, nothing occurs on SMS arrival.
What can I check?

**Comment by bogkonstantin** [comment]
Test using this website first, to be sure it is not web-server configuration problem:
https://webhook.site/

**Comment by narcisgarcia** [comment]
Feature request: Button to test URL with sample data, and application message with request result.

**Comment by peppi001** [comment]
I want to test it with android 4.1, but the app isn't installed. Is there a working version for android 4.1?

**Comment by bogkonstantin** [comment]
> I want to test it with android 4.1, but the app isn't installed. Is there a working version for android 4.1?

yes, just released

**Comment by narcisgarcia** [comment]
Just when upgraded to 2.2.3 from F-Doid, this phone began to trigger URL.

**Comment by narcisgarcia** [comment]
Now I realized another problem was to specify the word "Any" at Sender field instead of an asterisk.
