### ISSUE TITLE
wrong json format on multi line text

### ISSUE THREAD

**Issue by parsibox** [bogkonstantin/android_income_sms_gateway_webhook#27]
hi
your json format on multi line text is not valid
please review it
%text%
for example this is wrong
"first line
second line"

it should be like this :
"first line\nsecond line" ( this is true )

**Comment by parsibox** [comment]
this is sample of your wrong json
you can check it with this site https://jsonlint.com/

```
{
  "from":"+9890001027",
  "text":"خرید به صرفه در دیلی مارکت
٢ الی٤بهمن

پودر ماشین اکتیو۱۵۹۵۰ت
دستمال توالت تا۲۰%
رب خوشبخت۳۵۵۰۰ت
حبوبات تا۲۰%
چای شهرزاد تا۲۰%

لغو=١١",
  "sentStamp":1674367653000,
  "receivedStamp":1674367655339,
  "sim":"sim1"
}
```

**Comment by bogkonstantin** [comment]
The app doesn't trim \n symbols. Usually - the interface where you see JSON does that.

---
You can see it in screenshots - internal and external received data:

<img width="720" alt="image" src="https://user-images.githubusercontent.com/8061739/214385502-4d0bce05-51ee-4e9a-ae15-8bfad91c2b5b.png">
<img width="1579" alt="image" src="https://user-images.githubusercontent.com/8061739/214386043-2df54691-b844-49fb-8bbd-35127f096bc4.png">

---
When you copy-paste it (from the Raw Content on the 2nd screenshot) you are getting the wrong JSON:

<img width="471" alt="image" src="https://user-images.githubusercontent.com/8061739/214386395-2bee6ca2-ce83-4e98-81df-0b8e72c35c09.png">
