### ISSUE TITLE
No notifications sent - application not handling SMS?

### ISSUE THREAD

**Issue by mdeweerd** [bogkonstantin/android_income_sms_gateway_webhook#28]
Summary: I am not getting the notifications, everything seems to be set up correctly

- Installed the app using F-Android: v2.1.1.
- Autorised and Checked permissions (can access SMS).
- I have set up a web service (public IP) that logs anything that is posted.
- Tested it (Using "curl", data received & logged on the service).
- Configured the webhook (filtering on "*" and another on ".*" without the quotes);
- Made some initial trials - nothing received on the web service.
- Enabled USB debugging on my phone, installed a logcat capture applications, gave permissions.
- Made new trials;
- Checked the logs, filtered messages related to tech.bogo and incoming SMS, anonymized some data.  I could not see anything hinting that the app received the SMS.

[android_ui_andincoming.log](https://github.com/bogkonstantin/android_income_sms_gateway_webhook/files/10510947/android_ui_andincoming.log)

**Comment by Pheromon** [comment]
I have the same problem

**Comment by hamzamac** [comment]
I have the same problem too, i just installed the app from F-droid today and gave all the required permissions. Nothing happens unfortunately.

**Comment by hamzamac** [comment]
I tried with https://webhook.site/, still not request received

**Comment by hamzamac** [comment]
I read the release notes and found the new payload fields added

> More SMS details in payload (received timestamp, sim number, etc)
removining these mentioned fields fixed the error and i received the sms

**Comment by hamzamac** [comment]
Once it post the first sms with a reule without "sim", it seems to work if you delete the rule and create a new rule with all the payload fields
I tried with two phones and all worked after a rule with edited payload created

_maybe you just need to fake you are editing the paylod_

**Comment by mdeweerd** [comment]
@hamzamac Thank you for sharing your findings.

It does not work for me though.

**Comment by hamzamac** [comment]
Sorry to hear that, maybe we my issues caused by d different cause.

**Comment by lualex** [comment]
I run through AndroidStudio MacOS, it does not send data to webhook.site.
When an SMS arrives in LogCat, it writes the following:
2023-01-29 02:26:05.369 2261-2261/tech.bogomolov.incomingsmsgateway W/System: ClassLoader referenced unknown path: /system/vendor/framework/via-plugin.jar

tried to run your apk file, also does not send http.

**Comment by grenudi** [comment]
same

**Comment by bogkonstantin** [comment]
There was a bug with the initial start. Try new version (2.2.1)

**Comment by lualex** [comment]
Thanks! Now everything works!

By the way, my server does not accept messages when there was a code with this string URLConnection.setChunkedStreamingMode(0); in WebHookWorkRequest

I commented it out and everything started working. Maybe it will help someone.

**Comment by mdeweerd** [comment]
I only received the update today with F-Droid - I confirm the the issue is fixed for me as well, thank you!
