### ISSUE TITLE
Allow an optional Authorization header

### ISSUE THREAD

**Issue by darkostanimirovic** [bogkonstantin/android_income_sms_gateway_webhook#32]
Hi, thanks for open sourcing this.

I have an endpoint on [Supabase Edge Functions](https://supabase.com/docs/guides/functions) and it is secured by an auth token. What do you think about adding an optional `Authorization` header field to the modal?

Thanks

**Comment by bogkonstantin** [comment]
It is allowed - you have Headers parameter, put Auth header there
