### ISSUE TITLE
Payload body is empty

### ISSUE THREAD

**Issue by ruzzzz6312** [bogkonstantin/android_income_sms_gateway_webhook#33]
Latest version of the app on the Android 12 sends pretty clear headers but the "Body" is empty (payload)

**Comment by memsjava** [comment]
Me too i receive empty payload

**Comment by bogkonstantin** [comment]
check version 2.2.2

**Comment by andrisi** [comment]
Just installed 2.2.3 from from FDroid, but I seem to have the same issue on a Google Pixel 5. Header is set, but the body is empty.

**Comment by andrisi** [comment]
sorry, my mistake, there was a redirect happening on the POST URL...
