### ISSUE TITLE
Be able to configure MAX_ATTEMPT

### ISSUE THREAD

**Issue by anotherdevs** [bogkonstantin/android_income_sms_gateway_webhook#38]
It would be great to be able to configure MAX_ATTEMPT in the settings.
If 0 is defined it will try indefinitely. The data: receivedStamp and sentStamp can be used to filter out stale messages in the backend.

**Comment by bogkonstantin** [comment]
Done in [v.2.3.0](https://github.com/bogkonstantin/android_income_sms_gateway_webhook/releases/tag/v.2.3.0)
(except - without 0)
