### ISSUE TITLE
Please include all required signatures

### ISSUE THREAD

**Issue by IzzySoft** [bogkonstantin/android_income_sms_gateway_webhook#4]
The APK attached to releases lacks Jar signatures (v1 signing). Up to Android 7 (SdkVer 24), only v1 signing was known – so this APK cannot installed on such devices despite having minSdk set to 19. So when signing (I assume you're using v2 or v3 sigs), please make sure to include "lower" signatures as well – at least down to what's available at the specified minSdk.

If you could replace the latest APK with a properly signed one, that would be very much appreciated. Thanks in advance!

**Comment by bogkonstantin** [comment]
Updated v2.0 apk with both V1 and V2

**Comment by IzzySoft** [comment]
Thanks a lot, that worked out fine! Your app will now become available [in my repo](https://apt.izzysoft.de/fdroid/index/apk/tech.bogomolov.incomingsmsgateway) with the next sync in about 8h from now. I've put its metadata (description, screenshots etc) into [Fastlane](https://gitlab.com/snippets/1895688) format – if you wish I can provide that via a PR, so you're in full control of how your app is presented (Fastlane can also be used for the main [F-Droid](https://f-droid.org/) repo and Play Store as well in case you're interested).

Having the app there will hopefully raise some awareness (I'll also add it to my [corresponding app list](https://android.izzysoft.de/applists/category/named/office_contacts_shortmessage#group_82) once it's up) – and offer the user a "set-and-forget" as the F-Droid client informs them whenever updates are available (or even installs them automatically, depending on setup). If you like the idea, you can link there – I even have [a badge for that](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) :smile:

PS: should you want some metadata updated (e.g. a website link or donation page added), just let me know.

**Comment by bogkonstantin** [comment]
@IzzySoft thanks!

**Comment by IzzySoft** [comment]
I saw you've applied for F-Droid inclusion already, great! We'll process that as soon as we can (disclosure: I'm one of the F-Droid maintainers). So I guess you'll take my offer concerning Fastlane, as that's very much preferred by F-Droid for above mentioned reasons? That would make it easier for you to set it up as you'd then already have something to build on.
