### ISSUE TITLE
[Feature Request] Filter of sim card

### ISSUE THREAD

**Issue by tkhkbn** [bogkonstantin/android_income_sms_gateway_webhook#45]
Hi, would it be possible to add an option to only forward sms from a speicifc sms card (1 or 2)?

Thank you

**Comment by dotservice2024** [comment]
Константин здравствуйте! Тоже интересует этот вопрос, планируете ли добавить функцию, что бы смс пересылались с определенной сим-карты, что бы для каждой сим-карты можно было сделать свой фильтр?

**Comment by bogkonstantin** [comment]
Done in [v.2.3.0](https://github.com/bogkonstantin/android_income_sms_gateway_webhook/releases/tag/v.2.3.0)
