### ISSUE TITLE
suggestion: edit webhook settings

### ISSUE THREAD

**Issue by NienteSpigotSenzaJava** [bogkonstantin/android_income_sms_gateway_webhook#48]
that would be cool if the webhook could've been edited.

if i type the webhook url wrong, for example, i have to delete it and create it again, that would be great if an edit button existed.

**Comment by agroszer** [comment]
@bogkonstantin Please merge that PR and make a release!

**Comment by scottmconway** [comment]
@agroszer I have an up-to-date fork with this feature merged (and a release APK available). See this comment for more details:

https://github.com/bogkonstantin/android_income_sms_gateway_webhook/issues/65#issuecomment-1928687000

**Comment by bogkonstantin** [comment]
Done in [v.2.3.0](https://github.com/bogkonstantin/android_income_sms_gateway_webhook/releases/tag/v.2.3.0)
