### ISSUE TITLE
[Feature request] Support for Google RCS Messages

### ISSUE THREAD

**Issue by pmalecka** [bogkonstantin/android_income_sms_gateway_webhook#54]
When "Chat features" for messages app is on in the source device, some messages may be recieved this way.

Some details on how to do this:

https://stackoverflow.com/questions/75482120/how-to-retrieve-rcs-messages-from-android-devices

**Comment by bogkonstantin** [comment]
Duplicate:
https://github.com/bogkonstantin/android_income_sms_gateway_webhook/issues/46
