### ISSUE TITLE
Add a button to PAUSE the forwarding to a webhook

### ISSUE THREAD

**Issue by davchana** [bogkonstantin/android_income_sms_gateway_webhook#59]
Once we add a webhook by clicking the blue + plus button, it shows a red DELETE text to delete it. Please add a similar PAUSE text which, on clicked, will keep the webhook data but will not send any data until it is clicked again.

On clicking the PAUSE, the webhook is paused & button text is changed to RESUME.

It should ask for confirmation on each click.
Do you want to pause sending SMSs to this webhook?  | Do you want to resume sending SMSs to this webhook?

**Comment by bogkonstantin** [comment]
Done in [v.2.3.0](https://github.com/bogkonstantin/android_income_sms_gateway_webhook/releases/tag/v.2.3.0)
