### ISSUE TITLE
http not really working

### ISSUE THREAD

**Issue by rodjunger** [bogkonstantin/android_income_sms_gateway_webhook#6]
According to a quick google search, google really dislikes the idea of http requests so by default they're blocked and require some manifest changes to work, this is the long from logcat:

`06-08 16:13:11.725 17927 20254 E SmsGateway: Exception java.io.IOException: Cleartext HTTP traffic to redacted_ip not permitted
`

**Comment by rodjunger** [comment]
adding `android:usesCleartextTraffic="true"` to AndroidManifest.xml fixes it

**Comment by bogkonstantin** [comment]
Thank you for suggestion. Fixed that in [v2.01](https://github.com/bogkonstantin/android_income_sms_gateway_webhook/releases/tag/2.0.1)

**Comment by androtech143** [comment]
But still it's not working

**Comment by bogkonstantin** [comment]
@androtech143 would you please provide more information.
1 What app version do you use?
2 What Android version do you have?
3 How did you know that it doesn't work? Any logs?
