### ISSUE TITLE
Two configurations with different chat_id

### ISSUE THREAD

**Issue by dimkot** [bogkonstantin/android_income_sms_gateway_webhook#60]
When adding two configurations with different chat_id, only the last one is triggered.

#config1
number: +123456789
https://api.telegram.org/botXXXXXX/sendMessage?chat_id=XXXXXX
{"text":"%text%"}

#config2
number: +123456789
https://api.telegram.org/botXXXXXX/sendMessage?chat_id=YYYYYY
{"text":"%text%"}

I need to send sms through one bot to different bot users. How to fix it? (version 2.2.3)

**Comment by pmalecka** [comment]
having the same issue, also with wildcard (*) number filter. Only one of the webhooks gets triggered - the last one edited/added.

**Comment by pmalecka** [comment]
fixed in pull req: https://github.com/bogkonstantin/android_income_sms_gateway_webhook/pull/66

**Comment by bogkonstantin** [comment]
Done in [v.2.3.0](https://github.com/bogkonstantin/android_income_sms_gateway_webhook/releases/tag/v.2.3.0)
