### ISSUE TITLE
Is someone has merged these PR already ready in the queue and make a new APK?

### ISSUE THREAD

**Issue by olaxe** [bogkonstantin/android_income_sms_gateway_webhook#65]
Hello,
I don't want to be rude, I love this app and I would like to keep it alive. Maybe if the maintainer cannot applied theses PRs for any reason (IRL can be a bit** sometimes), someone can take over by cloning the repo. Personally, I can't due to my lack of knowledge for this language or the APK compilation.

**Comment by olaxe** [comment]
Thanks, I hope @bogkonstantin will come back but if not, I would love to try your fork and give you a feedback.

**Comment by scottmconway** [comment]
@olaxe I've merged all presently open PRs except for #63, as I don't see the need for it.

I've changed the application ID to "org.scottmconway.incomingsmsgateway", though everything else is the same.

You can find my latest release here:
https://github.com/scottmconway/android_income_sms_gateway_webhook/releases/tag/v2.2.4

**Comment by pmalecka** [comment]
@scottmconway I'm thinking it might be worth considering allowing anyone to raise issue in your fork repo. I have found a bug (related to the webhook editing) - that is only  present in your fork.

**Comment by pmalecka** [comment]
@scottmconway it's not an error per se, rather a limitation of the current implementation (undocumented). I might post a PR, when I have some spare time.
