### ISSUE TITLE
Changing the number of retries and the time interval between them

### ISSUE THREAD

**Issue by NabiKAZ** [bogkonstantin/android_income_sms_gateway_webhook#69]
> Every incoming SMS will be sent immediately to the provided URL. If the response code is not 2XX or the request ended with a connection error, the app will try to send again up to 10 times. Minimum first retry will be after 10 seconds, later wait time will increase exponentially. If the phone is not connected to the internet, the app will wait for the connection before the next attempt.

I need to change this message retry schedule. For example, instead of trying 10 times, try once. Or change the time between each attempt.
This can be added as an advanced settings feature in the app.

**Comment by bogkonstantin** [comment]
Done in [v.2.3.0](https://github.com/bogkonstantin/android_income_sms_gateway_webhook/releases/tag/v.2.3.0)
(except time between attempts - Android hanldles time)
