### ISSUE TITLE
php file

### ISSUE THREAD

**Issue by srlegha** [bogkonstantin/android_income_sms_gateway_webhook#7]
Please provide PHP API file

**Comment by bogkonstantin** [comment]
Actually there is no API needed. Just get POST input and decode it. [Example](https://www.geeksforgeeks.org/how-to-receive-json-post-with-php/). 

[Duplicated issue](https://github.com/bogkonstantin/android_income_sms_gateway_webhook/issues/1)

**Comment by jpph** [comment]
see https://github.com/bogkonstantin/android_income_sms_gateway_webhook/issues/21
