### ISSUE TITLE
Возможность отключения и редактирования фильтров.

### ISSUE THREAD

**Issue by dotservice2024** [bogkonstantin/android_income_sms_gateway_webhook#70]
Константин здравствуйте! Не могли бы добавить функцию, что бы фильтры можно было редактировать и ставить на паузу?

**Comment by bogkonstantin** [comment]
Done in [v.2.3.0](https://github.com/bogkonstantin/android_income_sms_gateway_webhook/releases/tag/v.2.3.0)
