### ISSUE TITLE
Feature request: add placeholder for local phone number

### ISSUE THREAD

**Issue by CalinBunea** [bogkonstantin/android_income_sms_gateway_webhook#81]
Hello,
We have a scenario where we would like to use multiple SIM cards to retrieve SMS and forward it to an endpoint. It would be useful if we could add in the payload the receiving SIM phone number, otherwise we will have to configure one endpoint on server for each of our physical phone numbers. Until then, we can add it by hand I guess...
Thank you.

**Comment by davchana** [comment]
If I understand correctly, you want this app to add the phone number the original SMS was sent (or where did this msg came out to, of these two sim cards in same). It allows "sim" argument. "sim": "%sim%"

**Comment by takielias** [comment]
@bogkonstantin @davchana 

When I use `"sim": "%sim%"` I got response like "sim":"sim1" But I need actual sim1 number. How can I get it?
