### ISSUE TITLE
I've written a telegram bot server (that anyone can self-host) that forwards messages from this app to telegram

### ISSUE THREAD

**Issue by AlexIII** [bogkonstantin/android_income_sms_gateway_webhook#87]
Hi! Thank you for publishing this app!

Just wanted to tell that I've written an open source telegram bot that accepts messages from your app and redirects them to telegram. 

This is not provided as a service, but rather people can host their own private bot instance (docker images available)

Sources, instructions:  https://github.com/AlexIII/messageredir

Cheers! 😊

**Comment by bogkonstantin** [comment]
You can send a message to the Telegram group without setting up a server for a bot, [here is a tutorial](https://github.com/bogkonstantin/android_income_sms_gateway_webhook?tab=readme-ov-file#send-sms-to-the-telegram)
